apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chinaplas-prod

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: production

images:
  - name: ghcr.io/gateszhangc/chinaplas-site
    newName: ghcr.io/gateszhangc/chinaplas-site
    newTag: 9a180baf7011c4f46a8bdb9c8f19ae3489a57b57
