apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chinaplas-prod

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: production

images:
  - name: ghcr.io/gateszhangc/chinaplas
    newName: ghcr.io/gateszhangc/chinaplas
    newTag: 0761badebf6908825927f0b1119360764e62214f
